name: My Panda CI
on: 
  push: 
    branches: [main] # means whenever something is pushed to main branch, do something 

jobs: 
  builds:
    runs-on: ubuntu-latest
    name: my build
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: setup go
        uses: actions/setup-go@v5.2.0
        with:
          go-version: 1.17.0

      - name: what is go version
        run: |
          go version
          ls
      - name: test the code
          go test
