name: My Panda CI
on: 
  push: 
    branches: [main] # means whenever something is pushed to main branch, do something 

jobs: 
  builds:
    runs-on: ubuntu-latest
    name: my build
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: setup go
        uses: actions/setup-go@v5.2.0
        with:
          go-version: 1.23.0

      - name: what is go version
        run: |
          go version
          ls
      - name: test the code
        run: |
          go test
      - name: checkout private repo remotely
        uses: actions/checkout@v4
        with:
          repository: EdythHo/sickandhiding
          path: hiding
          token: ${{ secrets.WHAT }}
      - name: list files in hidden dir
        run: |
          ls
          cd hiding
          ls
          cat README.md
