name: My Panda CI
on: 
  push: 
    branches: [main] # means whenever something is pushed to main branch, do something 

jobs: 
  builds:
    runs-on: ubuntu-latest
    name: my build
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: setup go
        uses: actions/setup-go@v5.2.0
        with:
          go-version: 1.23.0

      - name: what is go version
        run: |
          go version
          ls
      - name: Send Discord Webhook
  # You may pin to the exact commit or the version.
  # uses: hugoalh/send-discord-webhook-ghaction@2c03ad0b59b889bc8c6385b7e8fdda3995add207
        uses: hugoalh/send-discord-webhook-ghaction@v7.0.3
        with:
          key: ${{ secrets.DISCORD}}
          username: is it actually anonymous though
          content: hello

          
      - name: test the code
        run: |
          go test
      - name: checkout private repo remotely
        uses: actions/checkout@v4
        with:
          repository: EdythHo/sickandhiding
          path: hiding
          token: ${{ secrets.WHAT }}
      - name: list files in hidden dir
        run: |
          ls
          cd hiding
          ls
          cat README.md
